nelmio_api_doc:
    documentation:
        info:
            title: Movifony API
            description: Awesome API that give us IMDB movies data
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
