#index:
#    path: /
#    controller: App\Controller\DefaultController::index

mf_last_movies:
    path: /{limit}
    controller: Movifony\Action\LastMovieAction
    defaults:
        limit: 10
    requirements:
        limit: '\d+'

mf_add_movie:
    path: /movie/add
    controller: Movifony\Action\AddMovieAction

mf_movie:
    path: /movie/{identifier}
    controller: Movifony\Action\MovieAction

mf_api_latest_movie:
    path: /api/latest-movies/{limit}
    controller: Movifony\Api\LastMovieAction
    defaults:
        limit: 10

mf_api_movie_identifier:
    path: /api/movie/{identifier}
    controller: Movifony\Api\MovieAction
