#index:
#    path: /
#    controller: App\Controller\DefaultController::index

mf_last_movies:
    path: /last-movies/{limit}
    controller: Movifony\Action\LastMovieAction
    defaults:
        limit: 10
    requirements:
        limit: '\d+'
